laravel/fortify

- src/Actions/RedirectIfTwoFactorAuthenticatable.php
> Pass request through to the callback

- README.md
> bears, beets, battlestar galactica

- config/fortify.php
- stubs/fortify.php
Hello, I create this PR based on the [one I had initially created](https://github.com/laravel/fortify/pull/51#issue-489057317) and @taylorotwell [comment](https://github.com/laravel/fortify/pull/51#issuecomment-694838754). Here I have only updated the stub file with the ```middleware``` key. Regards
> [1.x] Update configuration stub with middleware option

- README.md
This view needs the request instance. See https://github.com/laravel/fortify/issues/57
> [1.x] Add request to code snippet

- stubs/UpdateUserProfileInformation.php
> [1.x] Remove unnecessary return

- README.md
Added correct location of CreateNewUser.php as it lives in app\Actions\Fortify\CreateNewUser.php not app\Actions\CreateNewUser.php
> Added correct location of CreateNewUser.php

- src/Rules/Password.php
> Correct property type in Rules\Password

- .github/workflows/tests.yml
- composer.json
Dependencies updated to support PHP8:
> [1.x] PHP8 Support

- README.md
I had to dig through the Fortify code to see how this was actually done, so I thought I would contribute to the documentation.
> [1.x] Instructions for the remember me login option

- config/fortify.php
- stubs/fortify.php
This PR adds documentation for the `prefix` and `domain` configuration options.
> [1.x] Add documentation for the `prefix` and `domain` configuration options

- README.md
Clarifies https://github.com/laravel/fortify/issues/141
> [1.x] Clarify guard modification

- UPGRADE.md
Document https://github.com/laravel/fortify/commit/8609af2292652234a70e4457d63ff1e10a510631
> [1.x] Update UPGRADE.md

- src/Actions/RedirectIfTwoFactorAuthenticatable.php
- src/Http/Requests/TwoFactorLoginRequest.php
> Revert "[1.x] Retrieve user through provider"

- routes/routes.php
Fixes https://github.com/laravel/fortify/issues/200
> [1.x] Move route outside $enableViews

- src/Http/Controllers/ConfirmablePasswordController.php
Removing duplicate implementation.
> Dedupliation: Use existing `session()->passwordConfirmed()`.

- src/Rules/Password.php
- tests/PasswordRuleTest.php
Adds a missing scenario for the password rule.
Fixes https://github.com/laravel/fortify/issues/212
> [1.x] Fix password rule

- src/Actions/CompletePasswordReset.php
- src/Fortify.php
- src/Http/Responses/LogoutResponse.php
- tests/FortifyServiceProviderTest.php
Some void methods which were still returning from other void methods and some dead code.
> [1.x] Cleanup code

- src/Contracts/PasswordUpdateResponse.php
- src/FortifyServiceProvider.php
- src/Http/Controllers/PasswordController.php
- src/Http/Responses/PasswordUpdateResponse.php
This PR aims to add custom response binding to password update feature.
> add password update custom response

- routes/routes.php
> fix: auth guard

- database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
Quick PR to switch to Laravel 8.37 >= anonymous migrations
This is inline with Laravel 9 defaults and recent commit to jetstream
> switch to anonymous migrations

- src/Http/Responses/FailedTwoFactorLoginResponse.php
The key for the error bag if 2FA authentication attempt was unsuccessful is incorrectly passed here.
> Fix incorrect key for error bag.

- CHANGELOG.md
- database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
- routes/routes.php
- src/Actions/ConfirmTwoFactorAuthentication.php
- src/Actions/DisableTwoFactorAuthentication.php
- src/Actions/RedirectIfTwoFactorAuthenticatable.php
- src/Events/TwoFactorAuthenticationConfirmed.php
- src/Fortify.php
- src/Http/Controllers/ConfirmedTwoFactorAuthenticationController.php
- src/TwoFactorAuthenticatable.php
- tests/AuthenticatedSessionControllerTest.php
- tests/TwoFactorAuthenticationControllerTest.php
Replaces https://github.com/laravel/fortify/pull/357
> [1.x] Confirmable 2FA

- .github/workflows/tests.yml
> PHP 8.2 Build

- .gitattributes
- .github/workflows/static-analysis.yml
- composer.json
- phpstan.neon.dist
This pull request adds type checking to this repository.
> [1.x] Adds type checking

- routes/routes.php
> Revert "Add rate limiter for a registration"

- src/Http/Responses/RecoveryCodesGeneratedResponse.php
This PR just fixes a response that was implementing the wrong contract.
> [1.x] Fix contract implementation

- tests/AuthenticatedSessionControllerTest.php
- tests/AuthenticatedSessionControllerWithTwoFactorTest.php
- tests/Models/User.php
- tests/Models/UserWithTwoFactor.php
- tests/OrchestraTestCase.php
- tests/TwoFactorAuthenticationControllerTest.php
* Abstract two factor authentication from `AuthenticatedSessionControllerTest` to `AuthenticatedSessionControllerWithTwoFactorTest`
* Use latest Testbench features.
> Test Improvements

- .github/SECURITY.md
>  Replace dead link in Security Policy

- src/Http/Controllers/PasswordResetLinkController.php
- tests/PasswordResetLinkRequestControllerTest.php
> [1.x] Support case insensitive password resets

- .github/workflows/tests.yml
> [1.x] Supports PHP 8.4
