routes/routes.php

This PR fixes #3. It renames the route that displays the register view to `register.show` to not conflict with the route that handles the form submission. With this all route names are unique which allows laravel to cache the routes.

Rename route to avoid name duplication

---

tests/AuthenticatedSessionControllerTest.php
tests/RecoveryCodeControllerTest.php
tests/TwoFactorAuthenticationControllerTest.php

- Using the `assertNotContains` to assert specific key is existed on result array.
- Using the `assertIsArray` to assert result value type is `array`.

Improve PHPUnit assertions

---

stubs/fortify.php

I was trying out Laravel 8/Jetstream and noticed a typo in the config file for fortify. This PR corrects that typo, nothing else

Fix a typo in fortify config stub

---

src/Actions/RedirectIfTwoFactorAuthenticatable.php
src/Http/Controllers/EmailVerificationPromptController.php
src/Http/Controllers/RegisteredUserController.php
src/Http/Controllers/TwoFactorAuthenticatedSessionController.php
src/Http/Controllers/TwoFactorAuthenticationController.php
src/Http/Controllers/TwoFactorQrCodeController.php
src/Http/Responses/FailedPasswordResetResponse.php
src/Http/Responses/FailedTwoFactorLoginResponse.php
src/Http/Responses/LoginResponse.php
src/Http/Responses/PasswordResetResponse.php
src/Http/Responses/TwoFactorLoginResponse.php
stubs/ResetUserPassword.php
stubs/UpdateUserPassword.php

This PR remove some unused imports and do the phpdocs cleanup listed below:
- Normalize all responses `toResponse`  phpdocs `@return` tag to be `\Symfony\Component\HttpFoundation\Response`
- Most of the Response classes are already using that as their phpdoc `@return`, I changed the others to do also use it, as come return `RedirectResponse` and `JsonResponse` which are not subclasses from Illuminate's `Response`. But all of them are subclasses of the Symfony one.
- Removed an unused param from phpdocs on `RegisteredUserController`'s `store` method

cleanup unused imports and phpdocs

---

src/FortifyServiceProvider.php

This PR introduces a way of setting a prefix for the authentication routes, which should enable the original use case proposed on #9. The implementation has been taken from other Laravel packages, such as Horizon, and I've kept the option named `path` to follow the convention (although I believe `prefix` would make more sense in this case).
This option wasn't added to the configuration file by default following the existing `domain` option, which is also missing from this file.

Allow specifying a prefix for routes

---

src/Fortify.php
src/FortifyServiceProvider.php

A mirror of Jetstream's https://github.com/laravel/jetstream/pull/67
Enables a user to call Fortify::ignoreRoutes() in a provider's register method to disable the default routes and provide their own.
Also enables publishing of default routes into userland.
Relevant are https://github.com/laravel/fortify/issues/9, https://github.com/laravel/fortify/pull/10

Provide a way of customizing/disabling the default routes

---

stubs/CreateNewUser.php

Currently, the CreateNewUser action has the exact same list of rules as the PasswordValidationRules trait that is used by ResetUserPassword and UpdateUserPassword. None of the projects I've worked on have ever purposefully had different validation rules between creating a password or updating it, and by having the same list in multiple places it is likely that some developers will miss the difference and make one way (creating versus updating/resetting) less secure than the other.

Use PasswordValidationRules trait in CreateNewUser action

---

composer.json

PHP 8 support was the only thing that was changed apparently. There's more changes in the diff between v7 and v8 but I think all of those are cosmetic/code cleanup.
Fixes https://github.com/laravel/jetstream/issues/151

google2fa v8

---

routes/routes.php
src/Contracts/FailedPasswordVerifyResponse.php
src/Contracts/PasswordVerifiedResponse.php
src/Contracts/VerifyPasswordViewResponse.php
src/Fortify.php
src/FortifyServiceProvider.php
src/Http/Controllers/VerifyPasswordController.php
src/Http/Responses/FailedPasswordVerifyResponse.php
src/Http/Responses/PasswordVerifiedResponse.php
src/Http/Responses/SimpleViewResponse.php
tests/VerifyPasswordControllerTest.php

This PR adds controller methods to support the 'password.confirm' middleware from Illuminate/Auth. 
The idea here is that this could eventually be used to implement a solution for issues like:
https://github.com/laravel/jetstream/issues/17
https://github.com/laravel/jetstream/pull/20
Where certain high risk actions (deleting an API key, deleting the user account, disabling 2FA, etc) could require a password verification prior to accessing the route. This is the pattern that Github follows (a re-auth redirect), and I think it's the most flexible approach.
Thanks for considering!

Add support for password confirmation middleware.

---

src/Contracts/TwoFactorLoginResponse.php
src/FortifyServiceProvider.php
src/Http/Controllers/TwoFactorAuthenticatedSessionController.php
src/Http/Responses/TwoFactorLoginResponse.php

By binding a contract for the TwoFactorLoginResponse, projects can substitute their own implementation in order to use some conditional routing in the login response (eg, admin user directed to admin dashboard).  This was already possible for the regular login, but not for the 2fa login.
Contract, classes and bindings replicate the LoginResponse, but keeps the original TwoFactor response.
Answers #31 feature request

[1.x] Switch the TwoFactorLoginResponse for a contract bound in container

---

config/fortify.php
src/Fortify.php
src/Http/Controllers/NewPasswordController.php
src/Http/Controllers/PasswordResetLinkController.php
stubs/fortify.php
tests/NewPasswordControllerTest.php
tests/PasswordResetLinkRequestControllerTest.php

This pull requests gives the ability to change the expected name of the variable in the request that holds the email address when making requests for forgotten passwords and when setting a new password. As it is implemented currently, the request variable name `email` is hard coded into the controllers for both requesting a password reset link and for setting the new password after visiting the reset link. This pull request adds a new config option, similar to the `username` option that is currently there, to allow for changing the expected variable name.
The implementation maintains the `email` name as a default value so that any existing applications should not experience any BC breaks.
The ability to set the expected name of the email address request variable via a config value makes …

[1.x] Allow the expected email address request variable to be changed

---

routes/routes.php

Addition for issue #13, This makes customizing routes easier.
Jetstream routes are also defined this way.
For instance: I needed to customize the url paths. So i turned the default routes off with the Fortify::ignoreRoutes(); option in my provider and copied the routes file. After that, the controller paths were broken. This commit fixes that scenario.

Make routes more dynamic

---

routes/routes.php

Previously, `/two-factor-challenge` routes are registered despite the TFA feature is disabled. This commit ensures routes registered only when TFA feature is enabled.

[1.x] Only register two-factor-challenge routes if TFA feature enabled

---

composer.json

This at least makes sure that composer can resolve Fortify's dependency on the Laravel framework properly.

[1.x] Add illuminate/support dependency

---

tests/AuthenticatedSessionControllerTest.php

Updating two factor authentication test to work without mock, like using real otp code generated from Google2FA package.

otp real test without mock

---

stubs/UpdateUserProfileInformation.php

When Email Verification is enabled, send a verification request to the new email address when a user updates their email address.
Optional commented line will null the email_verified_at value, which will force the user to verify the new address before doing anything else while logged in.

[1.x] Resend email verification after user update

---

src/Actions/AttemptToAuthenticate.php

Added the missing ```$request``` parameter to the ```throwFailedAuthenticationException``` call within the ```handleUsingCustomCallback``` method.

Added missing request to the throwFailedAuthenticationException method when using CustomCallback

---

src/Http/Controllers/NewPasswordController.php

I believe `, $password` was a typo or copied by mistake from the reset password documentation (here)[https://laravel.com/docs/8.x/passwords#resetting-the-password].

Removed unnecessary/unused variable

---

database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php

SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification.

fix test bug when use sqlite database

---

stubs/UpdateUserProfileInformation.php

The issue at hand has already been disclosed in #67 . In short, this PR prevents the package from forcing a user to reverify their email when simply updating their profile information (without changing their email).
Closes #67

Fix flawed logic in the UpdateUserProfileInformation action

---

src/Rules/Password.php

put a parameter to detect easily in translation files.
change this:
```
return __('The :attribute must be at least '.$this->length.' characters and contain at least one uppercase character.');
```
to:
```
return __('The :attribute must be at least :length characters and contain at least one uppercase character.', ['length' => $this->length]);
```

[1.x] Put length parameter for translation

---

src/Http/Controllers/EmailVerificationNotificationController.php
src/Http/Controllers/PasswordController.php
src/Http/Controllers/ProfileInformationController.php
src/Http/Controllers/RecoveryCodeController.php
src/Http/Controllers/TwoFactorAuthenticationController.php
src/Http/Responses/LogoutResponse.php
src/Http/Responses/PasswordConfirmedResponse.php
src/Http/Responses/RegisterResponse.php
src/Http/Responses/TwoFactorLoginResponse.php

Hi,
If client has requested for a JSON response, as in case of an AJAX request, then Fortify should return JSON response. Currently Fortify returns a plain response which may throw errors on client side (jQuery for ex).
This PR fixes this bug.
Thanks

Send JSON response if request is an AJAX request

---

src/Rules/Password.php

Hi! I have created this PR with the intention of adding in the password validation rules the option to require that the password contain or not special characters. 
Regards.

[1.x] Add option to force the password to have a special character.

---

src/Actions/ConfirmPassword.php
tests/ConfirmablePasswordControllerTest.php

Allow an empty password to be given and let it behave as an invalid password.
Before this fix, if the user leaves the field empty, a server error would occur. Now, a nice validation error will show.
---
Fixes https://github.com/laravel/fortify/issues/86

[1.x] Fix for empty password during confirmation

---

routes/routes.php

Add name to `/user/profile-information` and `/user/password` routes.
```php
Route::put('/user/profile-information', [ProfileInformationController::class, 'update'])
->middleware(['auth'])
->name('user-profile-information.update');
```
```php
Route::put('/user/password', [PasswordController::class, 'update'])
->middleware(['auth'])
->name('user-password.update');
```
Who extend Fortify package will easily access update profile and update password route by name.

Add name to Profile update and Password update routes.

---

src/Http/Responses/TwoFactorLoginResponse.php

This brings parity with the response send after a standard (non two-factor) login is completed. We're using Fortify to authenticate users for use with Passport, and if they're using two-factor auth, they are currently not redirected to the intended route (Passport callback route), due to this method not redirecting to the intended route.

Redirect to intended after two factor login

---

src/Http/Responses/SimpleViewResponse.php
tests/FortifyServiceProviderTest.php

This fix allow methods such as `Fortify::loginView` to return (amongst others) an Inertia response without running into this error: [Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given](https://flareapp.io/share/dmkdzMYP)
This happens because Laravel's router calls `->toResponse()` on `Responsable`, which SimpleViewResponse is an implementation of. After the object is converted to a response, other methods inside the router make sure that the response is properly generated.
However, because views such as Inertia's have their own Responsable implementation, this never gets triggered, because it never gets called by the SimpleViewResponse. This PR fixes this behaviour, preventing the user the need to do something like …

[1.x] Allow Fortify views to accept Responsable objects

---

stubs/CreateNewUser.php

This will let the validator use the actual name of the user table.

[1.x] Use the `Rule::unique` for new user validation

---

README.md

Generalizes readme with an updated ToC so it's the same as our other packages with docs in their readme.
I've also removed the anchors because they're not needed. Github generates these for us.

[1.x] Generalize readme

---

src/Actions/GenerateNewRecoveryCodes.php

This PR fixes the docblock description of the invoke method of the `GenerateNewRecoveryCodes` action, which currently has the same description as `DisableTwoFactorAuthentication`.

[1.x] Fix GenerateNewRecoveryCodes description

---

src/Http/Controllers/EmailVerificationNotificationController.php
src/Http/Controllers/EmailVerificationPromptController.php
src/Http/Controllers/VerifyEmailController.php
tests/EmailVerificationNotificationControllerTest.php
tests/EmailVerificationPromptControllerTest.php
tests/VerifyEmailControllerTest.php

This allows users to redirect to the intended URL instead of the home page, after they have verified their email address, as described in https://github.com/laravel/framework/pull/34808

Redirect to intended URL after email verification

---

README.md

Missing semi colon on **Customizing User Authentication** sample code.

Semi colon

---

src/Http/Controllers/AuthenticatedSessionController.php
tests/AuthenticatedSessionControllerTest.php

This PR resolves the issue of validating credentials twice when two-factor is disabled and the default login pipeline is used:
https://github.com/laravel/fortify/blob/c77b1832eed4223fa9e8fe1a5afc795c00c126a5/src/Http/Controllers/AuthenticatedSessionController.php#L83-L88
When two-factor authentication is disabled via the configuration file, users credentials are still validated twice, even though the action can be bypassed completely and another database call / `$authenticateUsing` callback execution can be avoided.
This is due to the `RedirectIfTwoFactorAuthenticatable` action, as well as the `AttemptToAuthenticate` action.
This was brought to light when overriding the `$authenticateUsing` callback, since it will be called twice, even when two-factor is omitted in `features`.

[1.x] Only use two factor action when enabled

---

README.md

the $request variable doesn't exist, to get the token, we should use the request() helper instead

[1.x] Update the way a token is retrieved

---

config/fortify.php
routes/routes.php
stubs/fortify.php

This PR is the implementation for the following issue: https://github.com/laravel/fortify/issues/128
It allows the user to disable routes returning views if they are using their own front-end (SPA, etc...).

[1.x] Add `disable_views` configuration

---

README.md

The current README.md does not have instructions on how to implement the password confirmation functionality even though that functionality exists in Fortify. I've added it and kept the instruction style similar to instructions in login, register, etc.

[1.x] Password Confirmation Docs

---

routes/routes.php

2FA routes `GET: /user/two-factor-qr-code` and `GET: /user/two-factor-recovery-codes` should not be disabled via `views` configuration option.
They are necessary / useful in SPA.

Fix 2FA disabled routes via `views` config

---

src/FortifyServiceProvider.php
stubs/fortify.php

Right now the `prefix` configuration option does not work because the ServiceProvider uses the wrong configuration key.

[1.x] Fix route prefix

---

src/Actions/AttemptToAuthenticate.php
src/Actions/RedirectIfTwoFactorAuthenticatable.php

This PR attempts to address the issue described in #145 
That issue states the `Failed` event is not being dispatched when a user provides faulty credentials. From my assessment this happens when 2-Factor Auth is enabled, or when the developer uses the `Fortify::$authenticateUsingCallback` feature.
Reason I found is the `Failed` event is only dispatched inside the `\Illuminate\Auth\SessionGuard@attempt` method after a failed login attempt.
As the `RedirectIfTwoFactorAuthenticatable` action is executed before the `AttemptToAuthenticate` in the default Fortify's login pipeline, when a user provides faulty credentials the `\Illuminate\Auth\SessionGuard@attempt` is not executed, and thus the `Failed` event never gets dispatched.
I added the code to dispatch the `Failed` event in 3 spots:
1. …

Fire Failed events

---

README.md

There's a small gotcha when disabling views that you still need a `password.reset` route for the password reset notification from Laravel. I've tried documenting this based on @rodrigopedra's great comment [here](https://github.com/laravel/fortify/issues/155#issuecomment-732531717) but I'm sure it can be improved even further.

[1.x] Document password reset gotcha when disabling views

---

README.md

This ToC isn't needed anymore now that the docs have moved to the main website.

[1.x] Remove ToC

---

src/Http/Controllers/AuthenticatedSessionController.php
src/Http/Controllers/ConfirmablePasswordController.php
src/Http/Controllers/NewPasswordController.php
src/Http/Controllers/RegisteredUserController.php
src/Http/Controllers/TwoFactorAuthenticatedSessionController.php

This is a partial fix for https://github.com/laravel/fortify/issues/171. After a successful two factor auth, the `PrepareAuthenticatedSession` action is never reached and thus a new CSRF token is never generated nor is the rate limiter reset. This PR adds these calls manually to the `TwoFactorAuthenticatedSessionController`. Ideally the `PrepareAuthenticatedSession` action would handle this but it can never be reached because two factor is being done in a new request.
There's also a few minor DocBlock fixes I sneaked in.

[1.x] Fix Two Factor prepare auth session

---

src/Actions/RedirectIfTwoFactorAuthenticatable.php
src/Http/Requests/TwoFactorLoginRequest.php

Re-send for https://github.com/laravel/fortify/pull/180

[1.x] Retrieve user through provider

---

stubs/UpdateUserPassword.php
tests/PasswordControllerTest.php

When no `current_password` key has been provided, the after callback of the validation of the request input throws an error exception instead of a proper validation exception. 
Fixes https://github.com/laravel/fortify/issues/174

[1.x] Fix missing current password

---

src/Rules/Password.php
tests/PasswordRuleTest.php

This fixes a bug when a non-string value is password as input for a password. For example, as an array through an API request from a third party.
https://github.com/laravel/fortify/issues/209

[1.x] Fix password rule

---

src/Http/Responses/RegisterResponse.php
tests/RegisteredUserControllerTest.php

This allows redirecting users to the intended URL after they've completed registration.

Redirect to intended URL after registration

---

.github/workflows/tests.yml
src/Http/Controllers/TwoFactorAuthenticatedSessionController.php
src/Http/Requests/TwoFactorLoginRequest.php
tests/AuthenticatedSessionControllerTest.php

This PR fixes an issue where the two factor form could still be displayed even though there's no user on session. This fix forces the controller to redirect to the login screen before the user can use the two factor view.
This PR unfortunately contains breaking changes to the method signature of the `create` method.
Fixes https://github.com/laravel/fortify/issues/231

[1.x] Fix two factor form without user

---

src/Http/Requests/TwoFactorLoginRequest.php

Alternative to https://github.com/laravel/fortify/pull/234
This fixes something I broke in https://github.com/laravel/fortify/pull/233 (unreleased). Apparently the user id gets pulled from the session when the form is submitted which makes sense. This means we cannot re-use the `challengedUser` method. I've instead opted to re-use some of the code from the `challengedUser` in the `hasChallengedUser` method. 
I tested this in an actual Jetstream app and it fixes the problem.
Thanks to @amiranagram for catching this.

[1.x] Fix two factor login check

---

src/Http/Responses/FailedTwoFactorLoginResponse.php

This should resolve https://github.com/laravel/fortify/issues/236
Also I was surprised to see that all the tests passed before and after the change. I would love to add tests for this as well, but I'm not sure how to test a two step verification challenge.
It shouldn't be an issue though, since there were no tests in the first place.

[2.x] Use code instead of email for the key

---

src/Http/Controllers/NewPasswordController.php
tests/NewPasswordControllerTest.php

I'm not really sure why this wasn't done before? These field are obviously required in the next step for the password broker. 
Fixes https://github.com/laravel/fortify/issues/244

[1.x] Require password and confirmation

---

src/Actions/RedirectIfTwoFactorAuthenticatable.php

My laravel-masterpass package can not work if jetstream is installed because here in fortify the underlying implementation is directly used in order to validate the user password.
There is no way for me to fix it from within my package. it should be fixed here in fortify.
The issue is: https://github.com/imanghafoori1/laravel-MasterPass/issues/38
This does not seem to be backward incompatible.

Better way of validating credentials

---

src/TwoFactorAuthenticatable.php

The generated QR-code doens't contain any value for the username if the username is another field than `email`. This cause some authenticators to crash. This pull request solves that issue by getting the username as defined in the config of Fortify.

fix: use configured username property for qr code url

---

src/Http/Controllers/NewPasswordController.php
tests/NewPasswordControllerTest.php

In some situations you don't need the password confirmation if this isn't part of the password reset flow.
See https://github.com/laravel/fortify/issues/253

[1.x] Remove password confirmation requirement

---

routes/routes.php

This resolves a conflict with the RedirectIfAuthenticated middleware.
Currently, the guest middleware is added to fortify routes without a specific guard. In some applications, you will be a guest with one guard but authenticated the next.
This PR changes the guest registration on the Fortify guest middleware to use the gust middleware with the guard specified in the Fortify config file.

[1.x] Restrict guest Middleware to Fortify's guard

---

routes/routes.php

After I included Fortify in an old Laravel project (with laravel ui), I was forced myself to use the url() helper instead the route() helper because some routes had no names on it. I added names to the following routes:
/user/two-factor-authentication => two-factor.toggle
/user/two-factor-qr-code => two-factor.qr-code
/user/two-factor-recovery-codes => two-factor.recovery-codes
Now I can use:
```php
<form method="POST" action="{{ route('two-factor.toggle') }}">
[...]
</form>
```
instead
```php
<form method="POST" action="{{ url('/user/two-factor-authentication') }}">
[...]
</form>
```
like other routes of Fortify. I used toggle because it enables and disables the 2FA for the user. Maybe a better name is found for that.
The tests can be modified to use route() helper but I don't know if …

[1.x] Naming 2FA routes for consistency

---

config/fortify.php
src/Fortify.php
src/Http/Controllers/EmailVerificationNotificationController.php
src/Http/Controllers/EmailVerificationPromptController.php
src/Http/Controllers/VerifyEmailController.php
src/Http/Responses/FailedPasswordConfirmationResponse.php
src/Http/Responses/FailedPasswordResetResponse.php
src/Http/Responses/LoginResponse.php
src/Http/Responses/LogoutResponse.php
src/Http/Responses/PasswordConfirmedResponse.php
src/Http/Responses/RegisterResponse.php
src/Http/Responses/TwoFactorLoginResponse.php

Resolve #77 
Added `redirects` on Fortify configuration.
```php
'redirects' => [
'login' => null,
'logout' => null,
'password-confirmed' => null,
'register' => null,
'email-verification' => null,
],
```
if not defined or null, `config('fortify.home')` will be used.

feat: redirection customization

---

routes/routes.php

this will allow us to implement our own inertia responses for verification route throttling.
right now it is hard-coded so it's impossible to change.

allow verification rate limiter to be configurable

---

src/TwoFactorAuthenticatable.php

Was quite surprised to find there is no straightforward boolean check for 2FA being enabled for a user.
To give credit where credit's due: this is taken from the article from @epndavis here: https://epndavis.com/blog/laravel-fortify-two-factor-authentication/
Happy to update documentation if this gets merged too.
Thanks!

Add a check for two factor auth being enabled.

---

src/Actions/AttemptToAuthenticate.php

Right now, it's only checking if `remember` is filled. For AJAX-based requests (such as with Inertia), passing `remember: false` still remembers their auth session.
Using `boolean` on a non-existent property also resolves to `false`.

Use `boolean` rather than `filled` for remember

---

stubs/FortifyServiceProvider.php

If a different type than string (like an array) is posted for the login route then an array to string error can occur. Doing a simple string type cast prevents this.
Fixes https://github.com/laravel/fortify/issues/332

[1.x] Fix an issue with array to string conversion

---

src/Http/Controllers/TwoFactorQrCodeController.php

Even when a user does not have 2FA enabled access to ```/user/two-factor-qr-code``` is allowed which throw 
```
Illuminate\Contracts\Encryption\DecryptException
The payload is invalid.
``` 
Or in production:
```
500 | SERVER ERROR
``` 
This commit checks if the authenticated user has 2FA enabled before returning a response, in the case the user does not have 2FA enabled an empty array will return to the user (following the same logic from ```/user/two-factor-recovery-codes```).

Check if authenticated user has 2FA enabled

---

config/fortify.php
routes/routes.php

We have an edge-case where we use the `auth` middleware as a middleware group containing the normal `auth` middleware, but also email verification and other auth-based middleware. It'd therefore be useful for us to customise the name of the auth middleware in Fortify.
This PR moves the `auth` name into the Fortify configuration and references it in the `routes.php` file. It uses `auth` as the default and so is fully backwards compatible, but gives the end user an option to configure it.

Customise the auth middleware name

---

src/Actions/DisableTwoFactorAuthentication.php
src/Actions/EnableTwoFactorAuthentication.php
src/Actions/GenerateNewRecoveryCodes.php
src/Actions/RedirectIfTwoFactorAuthenticatable.php
src/Events/RecoveryCodesGenerated.php
src/Events/TwoFactorAuthenticationChallenged.php
src/Events/TwoFactorAuthenticationDisabled.php
src/Events/TwoFactorAuthenticationEnabled.php
src/Events/TwoFactorAuthenticationEvent.php
tests/AuthenticatedSessionControllerTest.php
tests/RecoveryCodeControllerTest.php
tests/TwoFactorAuthenticationControllerTest.php

@driesvints Resolves your comments on #162 [here](https://github.com/laravel/fortify/pull/162#issuecomment-1006695992)

[1.x] Add 2fa Events

---

src/Contracts/VerifyEmailResponse.php
src/FortifyServiceProvider.php
src/Http/Controllers/VerifyEmailController.php
src/Http/Responses/VerifyEmailResponse.php

This PR adds a `VerifyEmailResponse` contract to let you modify the response returned after the email verification.
In some projects, you may need to change the default response. For example:
- to flash a success message in the session,
- or to have a dynamic redirection that depends on some user parameters.

Add VerifyEmailResponse contract

---

src/Http/Controllers/VerifyEmailController.php

Fixes the `VerifyEmailResponse` resolving.
The concrete class was passed to `app()` instead of the contract.

Fix VerifyEmailResponse resolving

---

.github/workflows/update-changelog.yml

Use the target branch of a release in the compare URL when updating the changelog through GitHub Actions.

[1.x] Use release target branch in changelog compare URL

---

src/Http/Requests/TwoFactorLoginRequest.php
src/Http/Responses/FailedTwoFactorLoginResponse.php
tests/AuthenticatedSessionControllerTest.php

At the moment, when a 2FA challenge is failed, the user is required to again provide its username and password. This, however, isn't standard behavior across most apps. Usually, you're not required to login again and are asked to again attempt a new 2FA code.
I've attempted a fix that keeps the `login.id` in session after a failed 2FA and the failed 2FA response now redirects to the 2FA form. The `login.id` key is only removed after a successful 2FA code. Together with the 2FA rate limiting I feel this should provide enough safety. I don't really see how asking the username/password again for every failed 2FA request is more safer.
If this is considered a breaking change then I can send this to master. 
See https://github.com/laravel/fortify/issues/351

[1.x] Prevent new login after failed 2FA

---

composer.json
src/LoginRateLimiter.php
tests/AuthenticatedSessionControllerTest.php

Exploit was found in the UI package that could bypass login throttle by replacing username characters with special characters. 
The same is possible in this package.
For more context around the exploit: https://github.com/laravel/ui/pull/216

[1.x] Fix Throttle Bypass Exploit

---

database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
src/Actions/ConfirmTwoFactorAuthentication.php
src/Actions/DisableTwoFactorAuthentication.php
src/Actions/RedirectIfTwoFactorAuthenticatable.php
tests/AuthenticatedSessionControllerTest.php
tests/TwoFactorAuthenticationControllerTest.php

Use Timestamps instead of boolean for confirming.

[2FA] Change to use timestamp for confirming 2fa

---

src/Actions/ConfirmTwoFactorAuthentication.php

This pull request prevents the user to send an empty confirm code and throw an exception to the code.
The following exception occurr if you try to confirm the two factor with an empty field:

Fix Exception when sending empty 2FA confirmation code

---

database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php

When trying to rollback the migrations i got this error
TypeError 
Unsupported operand types: array + bool
This commit solves the issue.

Unsupported operand types on rollback migration

---

src/FortifyServiceProvider.php
src/TwoFactorAuthenticationProvider.php

This PR allows to cache the 2FA timestamp of a token so it cannot be re-used during the time window of the 2FA engine. It's the solution detailed at https://github.com/antonioribeiro/google2fa#validation-window. 
Atm I'm storing the timestamp according with the token as its key in cache but the example from the link above associates it with the user. I don't see how that's important so I think the solution from this PR is probably fine. Happy to be proven otherwise if anyone has any objections.
The solution is backwards compatible because it introduces a new optional dependency for the `TwoFactorAuthenticationProvider` class.
Addresses concerns raised in https://github.com/laravel/fortify/issues/201

[1.x] Cache 2FA token timestamp

---

routes/routes.php

This fixes #367 
If you implement fortify without views, you have to hardcode the `password.confirm` route because no name is defined on the `post` route.
https://github.com/laravel/fortify/blob/b2de125809a742acf08bc6bcbe8f90f8ae92df29/routes/routes.php#L120-L121
If you have views enabled (`$enableViews = true`), you are saved because a `get` route is defined with the same route.
https://github.com/laravel/fortify/blob/b2de125809a742acf08bc6bcbe8f90f8ae92df29/routes/routes.php#L110-L114
Currently, this forces people using Fortify with a SPA/custom views (`$enableViews = false`), to hardcode the `password.confirm` route.
While this might not be the prettiest fix, it is a fix that will not cause breaking changes for those already using the package.

[1.x] Ensures route password.confirm is defined when not using views

---

src/Http/Responses/FailedTwoFactorLoginResponse.php

This PR solves an issue where a failed message was shown twice. This is technically a breaking change since we're removing the email key (the reason why we didn't in the related PR below). But the correct key is `code`.
See https://github.com/laravel/fortify/pull/360

[1.x] Fix double error message for failed 2FA response

---

routes/routes.php
src/Http/Controllers/TwoFactorSetupKeyController.php

* Added new route & controller to allow users to use setup key when enabling 2FA
This is necessary for jetstream to be able to support showing the setup key when using inertia

2FA setup key

---

src/TwoFactorAuthenticationProvider.php
stubs/fortify.php
tests/AuthenticatedSessionControllerTest.php

This PR addresses https://github.com/laravel/fortify/issues/324 , https://github.com/laravel/fortify/issues/374 
The aim is to allow a custom "window" to be set, as per the underlying package documentation: https://github.com/antonioribeiro/google2fa#validation-window
A fortify user could now set a window to 0 to instantly invalidate any old OTPs, or they could increase the current default setting of 1 to allow for a more generous window (setting this to 2 would allow up to 1 minute old OTPs to still be valid).

Added config option for custom OTP window

---

src/Http/Controllers/TwoFactorAuthenticatedSessionController.php

With this it is possible to get the `challengedUser()` within FailedTwoFactorLoginResponse.
Else you must implement your own checks on `login.id` in the response when you're doing something with the challenged user.
This is also used in: https://github.com/laravel/fortify/blob/7da6504f5f8a5fe6854dedaffc81ac497194ba56/src/Http/Requests/TwoFactorLoginRequest.php#L119

Call FailedTwoFactorLoginResponse::toResponse with TwoFactorLoginRequest

---

src/Http/Controllers/ConfirmedPasswordStatusController.php

In a scenario where you may need to extend the `ConfirmedPasswordStatusController` to a custom controller and you need to call the `show()` method inside a function with a return type hint you will get the worning below: 
```
Return value is expected to be '\Illuminate\Http\JsonResponse', '\Illuminate\Http\Response' returned 
``` 
Example:
```php
<?php
declare(strict_types=1);
namespace App\Http\Controllers\Auth;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
class ConfirmedPasswordStatusController extends \Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController
{
/**
* Get the password confirmation status.
*
* @param \Illuminate\Http\Request $request
*
* @return \Illuminate\Http\JsonResponse
*/
public function __invoke(Request $request): JsonResponse
{
return …
```

Fix the return type

---

src/TwoFactorAuthenticationProvider.php

Method `verifyKeyNewer` returns `true` when parameter `$oldTimestamp` is empty i.e. when there is no such code in cache. This allowed second usage of 2FA code:
`verifyKeyNewer` gets called with `null` as old timestamp, so it returns `true`. `true` is saved to cache as old timestamp.
`verifyKeyNewer` gets called with `true` as old timestamp, which later down the line gets converted to `1`. `verifyKeyNewer` uses current time and window value for creating starting timestamp and discards old timestamp, because it is smaller than created timestamp. So, if 2FA code is within the window, it gets accepted.
This pull request fixes this bug by creating new timestamp if `verifyKeyNewer` returned `true` and writing this new timestamp to cache.

Fix second usage of 2FA code

---

src/Http/Responses/FailedTwoFactorLoginResponse.php
tests/AuthenticatedSessionControllerTest.php

_This might be considered a breaking change..._
Currently when the user sends a `recovery_code`, any basic validation errors will be returned under the `recovery_code` key. But if the provided recovery code is incorrect, then the error is returned under the `code` key instead.
It's not a big deal if all errors are displayed at the top of the page. But if the errors are displayed alongside the specific fields (like [this Jetstream PR](https://github.com/laravel/jetstream/pull/1115#discussion_r941912210)), then the developer really needs to look in two places for recovery code errors.
This PR returns all recovery code errors under the `recovery_code` key.
The only time this may be a problem is if the user has worked around this quirk by *only* checking the `code` key for `recovery_code` …

[1.x] Return recovery errors under the `recovery_code` key

---

src/Fortify.php
src/Http/Controllers/ConfirmedTwoFactorAuthenticationController.php
src/Http/Controllers/EmailVerificationNotificationController.php
src/Http/Controllers/ProfileInformationController.php
src/Http/Controllers/RecoveryCodeController.php
src/Http/Controllers/TwoFactorAuthenticationController.php
src/Http/Responses/PasswordUpdateResponse.php

This addresses what I brought up in #408 that it's a little awkward having to compare the `status` flash to hard-coded strings like `two-factor-authentication-enabled` to appropriately show the correct messaging to the user. This provides constants on `Laravel\Fortify\Fortify` which provides clarity in end-user code that the expectation is that these flash messages are a result of an interaction with Fortify.
I've intentionally adopted [similar naming to that used by the constants in Laravel's `PasswordBroker`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Contracts/Auth/PasswordBroker.php).

Add and use constants for session flashes

---

src/Http/Requests/VerifyEmailRequest.php

There're 2 parameters in built-in function hash_equals, the first is "known_string" and second is "user_string".
[The notes in PHP manual of hash_equals](https://www.php.net/manual/en/function.hash-equals.php#refsect1-function.hash-equals-notes):
> It is important to provide the user-supplied string as the second parameter, rather than the first.
Otherwise, there's a question in stackoverflow.com about [Why is order of arguments in PHP's hash_equals() function important](https://stackoverflow.com/questions/27911597/why-is-order-of-arguments-in-phps-hash-equals-function-important)
In this commit, it changed parameter orders for hash_equals, because the "user_string" is provided by `$this->route('id')` and `$this->route('hash')`.
This commit will not break any existing features because it …

Parameters order with hash_equals

---

src/Http/Responses/FailedTwoFactorLoginResponse.php

Currently when user enters an invalid code and an empty recovery code (this is how jetstream sends the code) the error message key will always be `recovery_code` (and won't display in jetstream).

Fix error message when entering invalid 2fa code

---

src/Actions/ConfirmPassword.php

This change updates the `ConfirmPassword` action to use the `username` method from the `Fortify` class, to be inline with how the `username` is retrieved in other action classes.

Use Fortify username method on ConfirmPassword action

---

src/Http/Requests/TwoFactorLoginRequest.php

This change is similar to #411 which updates the parameter order for the `hash_equals` function.
The "known_string" is actually the `code` saved in the database and the "user_string" is the `recovery_code` from the incoming request.

Update parameter order for hash_equals function in TwoFactorLoginRequest

---

src/Http/Responses/PasswordResetResponse.php

Fixing issue #432 
Added additional check to skip url generation from route('login') if we decide not to use view routes from configuration file.
This fix will help end users to achieve better customization with views turned off.

Fix error while preparing PasswordResetResponse with views turned off

---

composer.json
database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
src/Contracts/CreatesNewUsers.php
src/Contracts/ResetsUserPasswords.php
src/Contracts/UpdatesUserPasswords.php
src/Contracts/UpdatesUserProfileInformation.php
stubs/CreateNewUser.php
stubs/FortifyServiceProvider.php
stubs/PasswordValidationRules.php
stubs/ResetUserPassword.php
stubs/UpdateUserPassword.php
stubs/UpdateUserProfileInformation.php
tests/Fixtures/Models/User.php
tests/PasswordControllerTest.php

Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.

[1.x] Uses PHP Native Type Declarations 🐘

---

stubs/FortifyServiceProvider.php

This PR ports two security fixes for MySQL/MariaDB from [`LoginRateLimiter`](https://github.com/laravel/fortify/blob/1.x/src/LoginRateLimiter.php#L92) to the service provider's rate limiter (that Fortify uses on a default installation):
- Protection against bypass attempts with different combinations of uppercase and lowercase characters (e.g. `uSer@example.com`): This fix has been included in `LoginRateLimiter` from the [beginning](https://github.com/laravel/fortify/commit/4f903075f01dddb46905a870f3a460fe17e1f461#diff-3cb814e6f9f9967e0516dda5c9fd4e8c3cb69394a03bad50bd7314156a8024c2R81) but not in the default rate limiter.
- Protection against bypass attempts with special characters (e.g. `uⓢer@example.com`): #354 fixed this in `LoginRateLimiter` but not in the default rate limiter.
I …

[1.x] Port security fixes to default login rate limiter

---

config/fortify.php
src/Actions/CanonicalizeUsername.php
src/Http/Controllers/AuthenticatedSessionController.php
src/Http/Controllers/ProfileInformationController.php
src/Http/Controllers/RegisteredUserController.php
stubs/fortify.php
tests/AuthenticatedSessionControllerTest.php
tests/ProfileInformationControllerTest.php
tests/RegisteredUserControllerTest.php

**Why**  
Using Postgres (and possibly other DBMS), comparisons are case-sensitive as opposed to MySQL.  
This causes issues where users would enter e.g. _**T**aylor<span>@</span>laravel.com_ on logging in but registered with _**t**aylor<span>@</span>laravel.com_, and receive a bad credentials error. This bites _every single installation of Fortify using Postgres_.
By storing the usernames in lowercase, and converting them before passing it to user-defined authentication logic, this problem just disappears.
**Backwards compatibility**  
I took care to not break BC anywhere:
- The option defaults to `true` for now, meaning usernames are case-sensitive by default. That way, nothing breaks for existing applications, including those with custom workarounds. It should probably be set to …

Added case-sensitivity option for usernames

---

composer.json

This pull request adds L11 support to fortify.
Also, drops:
- PHP 7.3, 7.4, 8.0.
- Laravel 8 and 9.

[develop] Adds L11 support

---

src/FortifyServiceProvider.php

This pull request makes the develop branch, the upcoming version version of Fortify that supports Laravel 11, to use `publishesMigrations` method.

[develop] Uses `publishesMigrations`

---

src/Rules/Password.php
stubs/PasswordValidationRules.php

Created a new PR with the feedback of Dries onto https://github.com/laravel/fortify/pull/510
This will deprecate the Fortify password rule and use the `Illuminate\Validation\Rules\Password` rule.
The `Illuminate\Validation\Rules\Password` rule has more functionality than the Fortify rule. For example this rule has mixed case and compromised check available.

Deprecate the password rule and use illuminate password rule

---

src/Actions/EnableTwoFactorAuthentication.php
src/Http/Controllers/TwoFactorAuthenticationController.php
tests/TwoFactorAuthenticationControllerTest.php

Add a `force` parameter that only overwrites existing two factor secret keys and recovery codes in the database if present when calling the enable two factor authentication action.
If the secret has already been set, the QR code may have already been shown to the end user, and this endpoint is erroneously called again - through a page refresh or some JS issue, the secret is overridden, rendering the code the end user just scanned useless without informing them that anything has changed.
When calling the `/user/two-factor-authentication` endpoint, the code now checks to see if the `two_factor_secret` is not `null` and assumes that it shouldn't overwrite it to prevent situations like this.
To force it to overwrite, you can pass the `force` parameter - which will fill out the two factor …

Don't overwrite an already two factor secret unless force = true

---

src/Http/Controllers/ConfirmablePasswordController.php
tests/ConfirmablePasswordControllerTest.php

Currently, the password confirmation endpoint uses PHP's inbuilt `time()` function. This does not consider `freezeSecond()` or `Date::setTestNow()`. Leading to inconsistent results during tests.
This update maintains compatibility with existing features as both `time()` and `->unix()` return a UNIX timestamp.

Use `Date` facade for storing the password confirmation timestamp

---

src/Console/InstallCommand.php
src/FortifyServiceProvider.php

This pull request adds `fortify:install` Artisan command.

[1.x] Adds `fortify:install` Artisan command

---

stubs/PasswordValidationRules.php

After running larastan with the max level I get the error `:passwordRules() return type has no value type specified in iterable type array.`. It's because the return type of the `passwordRules` method contains an array, and we don't specify the type. So by adding the type it solves the issue. 
Note: I'm not sure if it should be `array<mixed>` or `array<string>`.
Here the link to check the error:
https://phpstan.org/r/8eaf0f10-579e-49f9-96bf-6a1b55769231

Specify return type array type

---

composer.json

https://github.com/Bacon/BaconQrCode/releases/tag/v3.0.0

[1.x] Bacon QR 3.0 support

---

routes/routes.php
tests/AuthenticatedSessionControllerTest.php

It is currently possible to hit the `/logout` route as a guest. This means that the auth system "logs out" a `null` user.
This can occur in the real world when you:
1. Login to an app
2. Open the app in two tabs
3. Logout of one tab
4. Logout of the second tab
The framework will now logout a `null` user.
```php
Event::listen(fn (Logout $event) => assert($event->user === null));
```
I believe this is a good fix because:
1. Guests should not be able to visit the logout route. It is explicitly for authenticated users – just like the login route is explicitly for guests.
2. If you are listening for the logout event you are expecting a user.
3. The event is also typed (docblock) to require a user object.
4. Lastly, `laravel/breeze` does this, so it creates consistency for Jetstream and …

[1.x] Ensure logout route is authenticated

---

src/Actions/AttemptToAuthenticate.php
src/Actions/RedirectIfTwoFactorAuthenticatable.php

Introduced in Laravel Framwork 10.0.0: https://github.com/laravel/framework/pull/43163
This avoids having to override the method on application that can have separate fortify routes (and user guard) for frontend and backend.

[1.x] Use available `$name` property from `SessionGuard` if the value exists

---

src/Actions/RedirectIfTwoFactorAuthenticatable.php
tests/AuthenticatedSessionControllerWithTwoFactorTest.php

In Laravel 11, "automatic rehashing of user passwords when validating credentials" was added as a feature (https://github.com/laravel/framework/pull/48665). This PR ensures this feature also works when a user uses two-factor authentication.
When a user with two-factor enters their username and password, the user is not logged in because the user is redirected to the two-factor challenge page. This means the password rehashing is not triggered because it is only triggered when the user is immediately logged in when validating the credentials.

[1.x] Rehash password if required when user uses two factor

---

src/Events/TwoFactorAuthenticationFailed.php
src/Http/Controllers/TwoFactorAuthenticatedSessionController.php
tests/AuthenticatedSessionControllerWithTwoFactorTest.php

Hi Taylor,
Thank you for Fortify. It's our first time using it heavily, and we really enjoy the package so far.
In our project, we need to log 2FA events in a database table. Although Fortify already dispatches some events, we require one that is currently missing. This PR adds that event. I believe this is a low-risk change, and I'm happy to move the event call elsewhere if you prefer.

[1.x] Add TwoFactorAuthenticationFailed event

---

src/Events/TwoFactorAuthenticationVerified.php
src/Events/ValidTwoFactorAuthenticationCodeProvided.php
src/Http/Controllers/TwoFactorAuthenticatedSessionController.php
tests/AuthenticatedSessionControllerWithTwoFactorTest.php

In an app I'm working on we would like to store a timestamp in the session, when the user last verified their 2FA[^1]. While source-diving I didn't find an event that would be fired, when the 2FA code was verified. (There are only events for when the verification failed.)
This PR adds a new event that is being fired when a new session is being authenticated using 2FA. Adding an event listener for our usecase is now trivial.
---
I was contemplating if this event should be fired within the `TwoFactorAuthenticationProvider`, but as no other events are fired within that implementation I think the controllers is the right place for them.
[^1]: In our app, the admin panel is protected with a `RequireTwoFactorAuthentication`-middleware that periodically asks users to confirm their 2FA code. …

Fire ValidTwoFactorAuthenticationCodeProvided Event when 2FA session is authenticated

---

src/Events/RecoveryCodeReplaced.php
src/TwoFactorAuthenticatable.php

This PR triggers the RecoveryCodeReplaced event so that package users can listen to it. Looks like it was unintentionally omitted.

Dispatch RecoveryCodeReplaced Event

---

src/Http/Controllers/ConfirmedPasswordStatusController.php
tests/ConfirmablePasswordControllerTest.php

This would be useful for SPA application where we can register a timeout before checking the endpoint again.
Here, I chosen to use `X-Retry-After` instead of [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) since the documentation suggest the usage to be limited to `301`, `429` and `503` response status.

[1.x] Add `X-Retry-After` to `/user/confirm-password/status` response

---

src/Actions/EnableTwoFactorAuthentication.php
src/Contracts/TwoFactorAuthenticationProvider.php
src/TwoFactorAuthenticationProvider.php

Follow up of [https://github.com/laravel/fortify/issues/567](https://github.com/laravel/fortify/issues/567)
We need to ensure a minimum length for 2FA secret, current secret length by default is 80-bit (16 characters), but 128-bit (26 characters) is becoming minimum in some cases and the best default is 160-bit.
It's recommended to use 128-bit or 160-bit because some Authenticator apps may have problems with non-RFC-recommended lengths (Namely https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp).
Added some contextual config via : 
config('fortify-options.two-factor-authentication.secret-length', 16);
Retro compatible and define a security standard as expected by new RFC.

Adding context length configuration for 2FA to ensure better security standards

---

routes/routes.php

This PR fixes additional unnamed routes, such as login and register, when views are disabled.
It also fixes the issue with breadcrumbs potentially not working when GET routes don't have a name. (https://github.com/laravel/fortify/pull/368#issuecomment-1248084298)
In the current state, routes like login and register have to be hardcoded since they don't have names when views are disabled.

Fix unnamed routes when views are disabled (with original code formatting)

---

routes/routes.php

This PR should fix name issues (#573) (introduced in #571) for users that already use the names of the affected routes in their own route definitions.
Removed the unnecessary variables and conditions and added suffix to the POST route names referencing the assigned controller method. For example: `login.store`.

Rename `POST` routes to avoid regression bugs

---

src/Http/Controllers/RegisteredUserController.php
tests/RegisteredUserControllerTest.php

This pull request introduces support for the "Remember Me" functionality during the registration process in the `RegisteredUserController`. The changes ensure that users are logged in with the `remember` parameter based on the form input provided during registration.
1. Added `$request->boolean('remember')` in the `store` method of `RegisteredUserController` to handle the "Remember Me" option.
2. Updated tests in `RegisteredUserControllerTest`:
- Added a test to verify that the `remember` option works when set.
- Added a test to confirm that the login defaults to not remembering the user when the option is not set.
- Enhances user experience by allowing users to stay logged in if they choose to do so during registration.
- Backward-compatible, with no breaking changes introduced.
- All …

Add Remember Me Functionality to Registered User Login

---

src/TwoFactorAuthenticationProvider.php

This PR removes implicitly nullable parameters because these result in deprecation warnings for PHP 8.4.
https://www.php.net/manual/en/migration84.deprecated.php#migration84.deprecated.core.implicitly-nullable-parameter

Replace implicitly nullable parameters for PHP 8.4

---

database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php

When the laravel migration is run with TwoFactorAuthentication disabled it will not create the `two_factor_confirmed_at` field in database, but migration is completed.
If you would enable the TwoFactorAuthentication later this will result in a DBException and you have to create a new migration manually.
It would be better to just create the database field, which would allow enabled/disabling of 2FA without migration.

Changed migration of users table

---

src/Actions/DisableTwoFactorAuthentication.php

`DisableTwoFactorAuthentication` should always set `two_factor_confirmed_at` to `null` when it has a value

---

src/Actions/CanonicalizeUsername.php
src/Http/Controllers/PasswordResetLinkController.php
src/Http/Controllers/ProfileInformationController.php
src/Http/Controllers/RegisteredUserController.php

Current behavior of `CanonicalizeUsername` and checks related to `config('fortify.lowercase_usernames')` lead to empty fields being added to requests in some cases.
For example, if the request in the call to `src/Http/Controllers/ProfileInformationController.php` did not have whatever is set as `Fortify::username()` defined, an empty definition for `Fortify::username()` would be added to the request, potentially leading to issues during validation. This has happened to me and is the reason why I am making this pull request.

Prevent empty username fields from being added to requests
